<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>044ae3d3-dd19-41e6-bd68-c638f0eb16b3</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileContext>.</DockerfileContext>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Pics\Profile.jpg" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="9.0.8" />
      <PackageReference Include="Microsoft.Graph" Version="5.99.0" />
      <PackageReference Include="Microsoft.Identity.Web" Version="3.14.1" />
      <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.12" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="QRCoder" Version="1.7.0" />
      <PackageReference Include="RestSharp" Version="112.1.0" />
      <PackageReference Include="RestSharp.Newtonsoft.Json" Version="1.5.1" />
      <PackageReference Include="RestSharp.Serializers.SystemTextJson" Version="106.15.0" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Home\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Home\Privacy.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Fahrt_erstellen\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Mitfahren\Index.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <None Include="wwwroot\css\StyleSheet.css" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Views\Anfragen\" />
      <Folder Include="Views\Requests\" />
    </ItemGroup>

</Project>
